version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 3
    assignees:
      - "dinmukhamednurkaliyev"
    labels:
      - "type/chore"
      - "area/ci"
    groups:
      actions-all:
        patterns:
          - "*"
    commit-message:
      prefix: "chore(ci)"

  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    assignees:
      - "dinmukhamednurkaliyev"
    labels:
      - "type/chore"
      - "area/flutter"
    groups:
      flutter-safe-updates:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    commit-message:
      prefix: "chore(flutter)"

  - package-ecosystem: "gradle"
    directory: "/android"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    assignees:
      - "dinmukhamednurkaliyev"
    labels:
      - "type/chore"
      - "area/android"
    groups:
      android-all:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    commit-message:
      prefix: "chore(android)"
