name: fitness_tracker
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

workspace:
  - packages/core
  - packages/appearance
  - packages/localization
  - packages/home
  - packages/profile
  - packages/session

environment:
  sdk: ^3.10.8
  flutter: ^3.38.9

dependencies:
  appearance:
    path: packages/appearance
  core:
    path: packages/core
  flutter:
    sdk: flutter
  home:
    path: packages/home
  profile:
    path: packages/profile
  session:
    path: packages/session

dev_dependencies:
  alchemist: ^0.13.0
  bloc_test: ^10.0.0
  flutter_test:
    sdk: flutter
  melos: ^7.4.0
  mocktail: ^1.0.4
  mocktail_image_network: ^1.2.0
  very_good_analysis: ^10.1.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/

melos:
  scripts:
    analyze:
      run: melos exec -- flutter analyze
      description: Run flutter analyze for all packages.

    format:
      run: melos exec -- dart format .
      description: Run dart format for all packages.

    test:
      run: melos exec -- flutter test
      description: Run flutter test for all packages.

    clean:
      run: melos exec -- flutter clean
      description: Run flutter clean in all packages.

    get:
      run: melos bootstrap
      description: Install dependencies for all packages.
