name: localization
description: Localization package for fitness tracker application.
version: 0.1.0+1
publish_to: none
resolution: workspace

environment:
  sdk: ^3.10.8
  flutter: ^3.38.9

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^10.1.0

flutter:
  generate: true
