name: core
description: Core package for fitness tracker application.
version: 0.1.0+1
publish_to: none
resolution: workspace

environment:
  sdk: ^3.10.8
  flutter: ^3.38.9

dependencies:
  bloc: ^9.0.1
  dio: ^5.9.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  go_router: ^17.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^10.1.0

flutter:
  generate: true
